name: React test run
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the Code
        uses: actions/checkout@v3
      - name: Install nodejs(16)
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install project dependencies
        run: npm install
      - name: Run component tests
        run: npm test